apiVersion: apps/v1
kind: Deployment
metadata:
  name: twotierapp
  labels:
    app: twotierapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: twotierapp
  template:
    metadata:
      labels:
        app: twotierapp
    spec:
      containers:
        - name: twotierapp
          image: madhupdevops/two-tier-microservice-app:latest
          env:
            - name: MYSQL_HOST
              value: mysql
            - name: MYSQL_PASSWORD
              value: admin
            - name: MYSQL_USER
              value: root
            - name: MYSQL_DATABASE
              value: mydb
          ports:
            - containerPort: 5000
          imagePullPolicy: Always
