apiVersion: v1
kind: Service
metadata:
  name: two-tier-app-svc
spec:
  selector:
    app: two-tier-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
      nodePort: 30005
  type: NodePort
