apiVersion: v1
kind: Pod
metadata:
  name: two-tier-app-pod
  namespace: 2tier
spec:
  containers:
  - name: two-tier-app-pod
    image: trainwithshubham/flaskapp:latest
    env:
      - name: MYSQL_HOST
        value: mysql-service         # this is your mysql's service clusture IP, Make sure to change it with yours
      - name: MYSQL_PASSWORD
        value: "admin"
      - name: MYSQL_USER
        value: "root"
      - name: MYSQL_DB
        value: "mydb"
    ports:
      - containerPort: 5000
    imagePullPolicy: Always
    
