apiVersion: v1
kind: Service
metadata:
  name: appservice
spec:
  selector:
    app: twotierapp
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
      nodePort: 30004
  type: NodePort
